version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27018:27018
    command: mongod --port 27018
  spring-mongo-2:
    image: springboot-app
    ports:
      - 8080:8080
    links:
      - mongodb